{
 "title": "B3LB cluster monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "source", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Cluster usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bigbluebutton_meetings\" or r[\"_measurement\"] == \"bigbluebutton_recordings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active_meetings\" or r[\"_field\"] == \"participant_count\" or r[\"_field\"] == \"video_count\"  or r[\"_field\"] == \"voice_participant_count\" or r[\"_field\"] == \"recordings_count\" )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Participants over meetings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bigbluebutton_meetings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active_meetings\" or r[\"_field\"] == \"participant_count\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Cluster metrics over participants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "CPU (average) over participants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bigbluebutton_meetings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"participant_count\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")\n\nfrom(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "Memory (average %) over participants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bigbluebutton_meetings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"participant_count\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")\n\nfrom(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "Bandwidth (average) over participants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bigbluebutton_meetings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"participant_count\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")\n\nfrom(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_recv\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  }
 ]
}